@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTY4MTY3NTQ2MywiZXhwIjoxNjgxNzYxODYzfQ.lcr1Is1Y0GQMxSgWpENoFVimYBaZyKPZai5sI6zmbwI
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4MTY3NTk0MiwiZXhwIjoxNjgxNzYyMzQyfQ.6bAAOJ38JK8TWsUtci9FqE5v5vqcKoU_cm5P4SPY1zs
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjgxMzIzNzA0LCJleHAiOjE2ODE0MTAxMDR9.2dkY_z3SbEXBkBewehVcoxpH438gJFNFfEpXHOgnqh4
@modToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgxMTE3NTU2LCJleHAiOjE2ODEyMDM5NTZ9.FWSGOflxivGKLX5jldzZv5dWEdCxml0rKVoGgoFDDx8

# create user
POST https://localhost:8081/api/register HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "admin@gmail.com",
    "password": "test",
    "role": "admin"
}

###

# create user
POST https://localhost:8081/api/register HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "user@gmail.com",
    "password": "test",
    "role": "user"
}


###

# create user
POST https://localhost:8081/api/register HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "mod@gmail.com",
    "password": "test",
    "role": "mod"
}


###


# login
POST https://localhost:8081/api/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "user@gmail.com",
    "password": "test"
}

###

# test user permission
GET https://localhost:8081/api/test/user HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{modToken}}

###

GET https://localhost:8081/api/test/mod HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{modToken}}

###

GET https://localhost:8081/api/test/admin HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{userToken}}
###

# get all doors

GET https://localhost:8081/api/getAllDoors HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}


###

# create new door

POST https://localhost:8081/api/addDoor HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "doorName": "MULT-LAB-003",
    "doorLocation": "KICT-LV05"
}


###

#remove door

POST https://localhost:8081/api/removeDoor HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "doorId": "8"
}

###

# giver permission to user

POST https://localhost:8081/api/giveAccess HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "doorId": "4",
    "userId": "3"
}


###

# revoke user permission

POST https://localhost:8081/api/revokeAccess HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "doorId": "8",
    "userId": "1"
}



### 

# open door

POST https://localhost:8081/api/openDoor HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "userId": "2",
    "doorId": "100"
}



###

# close door
POST https://localhost:8081/api/closeDoor HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}
    
{
    "userId": 3,
    "doorId": "1"
}

###

# update userinfo

POST https://localhost:8081/api/updateUserInfo HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "userId": 1,
    "email": "admin@gmail.com",
    "password": "test",
    "role": "admin"
}


###

# get all doors with access

GET https://localhost:8081/api/getAllDoorsWithAccess HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "userId": 1
}


###

# get all doors with access

GET https://localhost:8081/api/getAllUserDoorsWithAccess HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "userId": 3
}


###

# upddate info

POST https://localhost:8081/api/updateInfo HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "userId": 3,
    "email": "update@gmail.com",
    "password": "1234",
    "role": "admin"
}


###

# add door passcode
POST https://localhost:8081/api/addDoorPasscode HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "doorId": 1,
    "doorPasscode": "1234"
}


###

# remove door passcode

POST https://localhost:8081/api/revokeDoorPasscode HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "doorId": 1
}


###

# adduser to permission with code

POST https://localhost:8081/api/addDoorWithPasscode HTTP/1.1
Content-Type: {{contentType}}
x-access-token: {{token}}

{
    "userId": 1,
    "doorId": 10,
    "doorPasscode": "1234"
}

